// GENERATED by scripts/build-tt-entry.mjs. Edit canonical sources, not this file.
// Canonical source: src/hostCompatibilityCore.js
// TT Project Contract v1, not an invented SillyTavern event or private engine API.
// https://github.com/Darkatse/TauriTavern/blob/9693a4ec47cd4552f90878bccab453f176de0f18/docs/API/ChatSurface.md
// Register this lightweight bridge during extension evaluation, before projection.
// Heavy consumers may subscribe later; only currently mounted host leases are replayed.
const PARTICIPANT_ID = 'rabbitmirror/message-runtime';
const SURFACES = new Set(['fullscreen-window', 'backdrop', 'free-window', 'viewport-host']);

// Only retain a fixed diagnostic code, never the host exception/body. TT v1
// freezes registration at the first projection; reattempting or launching a
// legacy observer after that point would violate managed DOM ownership.
function registrationFailureReason(error) {
    const message = typeof error?.message === 'string' ? error.message : '';
    if (message.includes('must register before the first projection')) return 'late-projection';
    if (message.includes('participant already registered')) return 'duplicate-participant';
    return 'host-rejected';
}

function toDisposer(value) {
    if (value === undefined || value === null) return null;
    if (typeof value === 'function') return value;
    if (typeof value?.then === 'function') throw new TypeError('RabbitMirror ChatSurface handlers must return synchronous cleanup');
    if (typeof value?.dispose === 'function') return () => value.dispose();
    throw new TypeError('RabbitMirror ChatSurface cleanup must be a function or disposable');
}

function createRabbitMirrorHostCompatibility(hostGlobal = globalThis, diagnostics = {}) {
    let recordTtSurface = diagnostics.record || (() => {});
    let ttSurfaceNow = diagnostics.now || (() => 0);
    let disposed = false;
    let initialized = false;
    let managed = false;
    let registration = null;
    let status = Object.freeze({ host: 'sillytavern', managed: false, registered: false, protocolVersion: null, errorCode: '' });
    const subscriptions = new Map();
    const mounted = new Map();

    function reportFault(error) {
        status = Object.freeze({ ...status, errorCode: 'CHAT_SURFACE_CONSUMER_FAILED' });
        registration?.fault?.(error);
    }

    function disposeCallback(lease, id) {
        const dispose = lease.cleanups.get(id);
        lease.cleanups.delete(id);
        lease.delivered.delete(id);
        dispose?.();
    }

    function deliver(lease, subscription) {
        if (!lease.active || lease.context.signal.aborted || lease.delivered.has(subscription.id)) return;
        const callback = subscription[lease.kind];
        if (typeof callback !== 'function') return;
        lease.delivered.add(subscription.id);
        // 仅诊断：关闭时 ttSurfaceNow() 返回 0，不会调用 performance.now()。
        const ttStart = ttSurfaceNow();
        const dispose = toDisposer(callback(lease.context));
        recordTtSurface('deliver', {
            sub: subscription.id, phase: lease.kind, mesid: lease.context.mesid,
            ms: ttStart ? performance.now() - ttStart : 0,
        });
        // A handler can synchronously release its own mount or subscription.
        if (!lease.active || !subscriptions.has(subscription.id) || lease.context.signal.aborted) dispose?.();
        else if (dispose) lease.cleanups.set(subscription.id, dispose);
    }

    function openLease(kind, context) {
        if (disposed) return () => {};
        if (!context?.element || !context?.content || !Number.isInteger(context?.mesid)
            || typeof context?.signal?.addEventListener !== 'function') {
            throw new TypeError('RabbitMirror requires a valid TT ChatSurface mounted context');
        }
        if (context.signal.aborted) return () => {};
        let record = mounted.get(context.element);
        if (!record) {
            record = { didMount: null, didCommitContent: null };
            mounted.set(context.element, record);
        }
        record[kind]?.dispose();
        // Replacing the final lease can remove the old record from the map.
        mounted.set(context.element, record);
        const lease = { kind, context, active: true, cleanups: new Map(), delivered: new Set(), dispose: null };
        const dispose = () => {
            if (!lease.active) return;
            recordTtSurface('lease-dispose', { mesid: context.mesid, phase: kind });
            lease.active = false;
            context.signal.removeEventListener('abort', dispose);
            let firstError = null;
            for (const id of [...lease.delivered]) {
                try { disposeCallback(lease, id); } catch (error) { firstError ??= error; }
            }
            if (record[kind] === lease) record[kind] = null;
            if (!record.didMount && !record.didCommitContent) mounted.delete(context.element);
            if (firstError) reportFault(firstError);
        };
        lease.dispose = dispose;
        record[kind] = lease;
        context.signal.addEventListener('abort', dispose, { once: true });
        try {
            for (const subscription of subscriptions.values()) deliver(lease, subscription);
        } catch (error) {
            dispose();
            throw error;
        }
        return dispose;
    }

    function initialize() {
        if (initialized || disposed) return status;
        initialized = true;
        const host = hostGlobal?.__TAURITAVERN__;
        const api = host?.api?.chatSurface;
        if (!host) return status;
        status = Object.freeze({ ...status, host: 'tauritavern', protocolVersion: api?.protocolVersion ?? null });
        if (typeof api?.isManagedOwnershipRequired !== 'function') return status;
        try { managed = api.isManagedOwnershipRequired() === true; }
        catch {
            // Ownership is unknown, so do not launch an unmanaged repair watcher.
            managed = true;
            status = Object.freeze({ ...status, managed, errorCode: 'CHAT_SURFACE_OWNERSHIP_UNAVAILABLE' });
            return status;
        }
        status = Object.freeze({ ...status, managed });
        if (!managed) return status;
        if (api.protocolVersion !== 1 || typeof api.registerParticipant !== 'function') {
            status = Object.freeze({ ...status, errorCode: 'CHAT_SURFACE_PROTOCOL_UNSUPPORTED' });
            return status;
        }
        try {
            registration = api.registerParticipant({
                id: PARTICIPANT_ID,
                protocolVersion: 1,
                didMount: context => openLease('didMount', context),
                didCommitContent: context => openLease('didCommitContent', context),
            });
            status = Object.freeze({ ...status, registered: true });
        } catch (error) {
            status = Object.freeze({ ...status, errorCode: 'CHAT_SURFACE_REGISTRATION_FAILED',
                registrationFailure: registrationFailureReason(error) });
        }
        return status;
    }

    function subscribe(definition) {
        if (disposed) return () => {};
        initialize();
        if (!definition || typeof definition.id !== 'string' || !definition.id.trim()) {
            throw new TypeError('RabbitMirror ChatSurface consumer requires a stable id');
        }
        for (const kind of ['didMount', 'didCommitContent']) {
            if (definition[kind] !== undefined && typeof definition[kind] !== 'function') {
                throw new TypeError(`RabbitMirror ChatSurface ${kind} must be a function`);
            }
        }
        if (!managed || !status.registered) return () => {};
        if (subscriptions.has(definition.id)) throw new Error(`Duplicate RabbitMirror ChatSurface consumer: ${definition.id}`);
        const subscription = { id: definition.id, didMount: definition.didMount, didCommitContent: definition.didCommitContent };
        subscriptions.set(subscription.id, subscription);
        let active = true;
        const unsubscribe = () => {
            if (!active) return;
            active = false;
            subscriptions.delete(subscription.id);
            let firstError = null;
            for (const record of mounted.values()) {
                for (const kind of ['didMount', 'didCommitContent']) {
                    if (!record[kind]) continue;
                    try { disposeCallback(record[kind], subscription.id); } catch (error) { firstError ??= error; }
                }
            }
            if (firstError) reportFault(firstError);
        };
        try {
            for (const record of mounted.values()) {
                for (const kind of ['didMount', 'didCommitContent']) {
                    if (record[kind]) deliver(record[kind], subscription);
                }
            }
        } catch (error) {
            unsubscribe();
            reportFault(error);
            throw error;
        }
        return unsubscribe;
    }

    function dispose() {
        if (disposed) return;
        disposed = true;
        let firstError = null;
        for (const record of [...mounted.values()]) {
            for (const kind of ['didMount', 'didCommitContent']) {
                try { record[kind]?.dispose(); } catch (error) { firstError ??= error; }
            }
        }
        subscriptions.clear();
        mounted.clear();
        recordTtSurface = () => {};
        ttSurfaceNow = () => 0;
        if (firstError) reportFault(firstError);
    }

    return Object.freeze({
        initialize,
        dispose,
        attachDiagnostics(next = {}) {
            if (disposed) return;
            recordTtSurface = typeof next.record === 'function' ? next.record : (() => {});
            ttSurfaceNow = typeof next.now === 'function' ? next.now : (() => 0);
        },
        isManaged: () => { initialize(); return managed; },
        getStatus: () => { initialize(); return status; },
        subscribe,
        getMountedMessages() {
            initialize();
            return [...mounted.values()].map(record => (record.didCommitContent || record.didMount)?.context).filter(Boolean);
        },
        externalPlacementParent(message) { initialize(); return managed ? message : null; },
        applySurface(element, surface) {
            if (!SURFACES.has(surface)) throw new TypeError('Unsupported RabbitMirror host surface');
            if (!hostGlobal?.__TAURITAVERN__?.api?.layout || typeof element?.setAttribute !== 'function') return false;
            element.setAttribute('data-tt-mobile-surface', surface);
            return true;
        },
    });
}

// Canonical source: scripts/tt-entry.template.js
// Build source only. build-tt-entry.mjs embeds only the import-free bridge
// above this code. No top-level await or UI work may delay registration.
const BOOT_COHORT = '1.5.49-ttimmediate1';
const BOOT_VERSION = '1.5.49';
const ttHost = globalThis.__TAURITAVERN__;
const boot = {
    cohort: BOOT_COHORT,
    rootUrl: new URL('./', import.meta.url).href,
    host: ttHost,
    bridge: ttHost ? createRabbitMirrorHostCompatibility(globalThis) : null,
    cancelled: false,
    coreState: 'loading',
};
globalThis.__rabbitMirrorTtBootstrap = boot;
const bootIsCurrent = () => !boot.cancelled && globalThis.__rabbitMirrorTtBootstrap === boot;
// This is synchronous and runs before ANY core/UI/settings module request.
boot.bridge?.initialize();
if (ttHost) globalThis.__rabbitMirrorRuntimeVersion = BOOT_VERSION;

let coreModule = null;
let cleanupKind = '';
let appliedCleanupKind = '';

// TT awaits this interceptor even while the asynchronous core is loading.
// Never let a generation slip through without the existing prompt/guard contract.
const earlyInterceptor = async (...args) => {
    if (!bootIsCurrent()) return;
    const mod = await corePromise;
    if (!bootIsCurrent()) return;
    if (!mod) {
        if (typeof args[2] === 'function') args[2](true);
        throw new Error('RabbitMirror core failed to load; restart after checking extension files');
    }
    return mod.rabbitMirrorGenerateInterceptor(...args);
};
globalThis.rabbitMirrorGenerateInterceptor = earlyInterceptor;
boot.interceptor = earlyInterceptor;
const corePromise = import('./index.js?rmv=1.5.49-ttimmediate1').then(mod => {
    coreModule = mod;
    boot.coreState = boot.cancelled ? 'disabled' : 'ready';
    applyCoreCleanup();
    return mod;
}).catch(() => {
    boot.coreState = boot.cancelled ? 'disabled' : 'failed';
    return null;
});

function applyCoreCleanup() {
    if (globalThis.__rabbitMirrorTtBootstrap !== boot || !coreModule || !cleanupKind || appliedCleanupKind === cleanupKind) return;
    appliedCleanupKind = cleanupKind;
    if (cleanupKind === 'clean') coreModule.onClean();
    else coreModule.onDisable();
}
function stopBootstrap(kind) {
    cleanupKind = kind === 'clean' || cleanupKind === 'clean' ? 'clean' : 'disable';
    boot.cancelled = true; // Keep the tombstone for an already-in-flight import.
    boot.coreState = 'disabled';
    boot.bridge?.dispose();
    if (globalThis.rabbitMirrorGenerateInterceptor === earlyInterceptor) delete globalThis.rabbitMirrorGenerateInterceptor;
    applyCoreCleanup();
}
export function onDisable() { stopBootstrap('disable'); }
export function onClean() { stopBootstrap('clean'); }
// Observation only: this does not start another import, runtime or request.
export function whenRabbitMirrorRuntimeReady() { return corePromise; }
